version: "3.9"

services:
  web:
    environment:
      - DATA_PATH=/data
      - DB_NAME=starwars
      - DB_USER=sw_app
      - DB_PASSWORD=123456
      - DB_PORT=5432
      #- DB_HOST=db
    build: .
    volumes:
      - /Users/jakub/data:/data
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres: